using System.Globalization;
using System.Reflection;
using System.Text;

using Praxis.TargetArchitecture.Entities;
using Praxis.TargetArchitecture.Features.Api.Architecture.GetOverview;

namespace Praxis.TargetArchitecture.AppInfrastructure;

/// <summary>
/// Emits the backend-owned values the frontend needs but cannot infer from the OpenAPI
/// document: shared constants, and a display label per enum member. The enums themselves
/// already reach the frontend through OpenAPI, so only the labels are written here.
/// </summary>
public static class PraxisTypescriptGenerator
{
    private const string OutputPath = "../../frontend/src/models/generated/constants.ts";

    public static async Task GenerateFiles()
    {
        if (!PraxisEnvironments.WriteTypescriptFiles)
        {
            return;
        }

        await File.WriteAllTextAsync(OutputPath, BuildTypescript());
    }

    public static string BuildTypescript()
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* This file is autogenerated by the backend. Do not modify manually. */");
        builder.AppendLine();

        builder.AppendLine("import { ArchitectureLayer, ArchitectureTag } from \"./types.gen\"");
        builder.AppendLine();

        AppendConstants(builder, typeof(ArchitectureConstants));
        AppendLabels<ArchitectureLayer>(builder, "layerLabels", ArchitectureLabels.For);
        AppendLabels<ArchitectureTag>(builder, "tagLabels", ArchitectureLabels.For);

        return builder.ToString();
    }

    private static void AppendConstants(StringBuilder builder, Type constantsType)
    {
        foreach (var field in constantsType.GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            if (!field.IsLiteral || field.FieldType != typeof(int))
            {
                continue;
            }

            var value = Convert.ToInt32(field.GetRawConstantValue(), CultureInfo.InvariantCulture);
            builder.AppendLine($"export const {field.Name} = {value}");
        }

        builder.AppendLine();
    }

    private static void AppendLabels<TEnum>(StringBuilder builder, string labelsName, Func<TEnum, string> label)
        where TEnum : struct, Enum
    {
        var name = typeof(TEnum).Name;

        builder.AppendLine($"export const {labelsName}: Record<{name}, string> = {{");

        foreach (var value in Enum.GetValues<TEnum>())
        {
            builder.AppendLine($"    [{name}.{value}]: \"{label(value)}\",");
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }
}
